# 2 - Sudoku 

  O objetivo é preecncher uma grelha de *N²*$\times$*N²* com inteiros positivos no intervalo de 1 até *N²*, satisfazendo as seguintes regras:

  *   Cada inteiro no intervalo de 1 até *N²* ocorre só uma vez em cada coluna, linha e secção *N*$\times$*N*.
  *   No início do jogo uma fracção *0* $\leq \alpha <$ 1 das N⁴ casas da grelha são preenchidas de forma consistente com a regra anterior.

Pretende-se: 

  *   Construir um programa para inicializar a grelha a partir dos parâmetros N e $\alpha$.
  *   Construir soluções do problema paras as combinações de parâmeteos *N* $\in$ {3,4,5,6} e $\alpha \in$ {0.0, 0.2, 0.4, 0.6} e tirar conclusões da complexidade computacional destas soluções.

**Análise do Problema** 

  É esperado receber um *N* e um $\alpha$, por parte do utilizador, onde *N* corresponde ao tamanho de cada secção do Sudoku que será representado e $\alpha$ a fracção de casas já preenchidas pela máquina. 

  Deste modo, o método utilizado para a construção do Sudoku foi a de um grafo. A estrutura do grafo tem a seguinte forma, *(n, A)*, onde *n* corresponde ao nodo e *A* corresponde há lista de nodos que têm uma relação com ele, ou seja, 
pertemcem à mesma secção, linha ou coluna. 

Seguidamente, a função **ip_color2** que verifica todas as relações entre os nodos e atribui uma cor diferente para nodos adjacentes. Deste modo, não é possivel existir a mesma cor numa mesma secção, linha ou coluna. 

Finalmente, como cada cor é lhe atribuído um número $\varkappa \in$*N²*. O grafo é representado em forma de matriz com cada cor do nodo a representado como um número.    










In [ ]:
!pip install ortools #não é necessário executar sempre

In [5]:
# importe de bibliotecas importantes para a execução do código
import numpy as np
import math 
import networkx as nx
import time
from ortools.linear_solver import pywraplp

In [9]:
def checkSquare(x1,y1,x2,y2,size):
        if x1//size == x2//size and y1//size == y2//size:
            return True
        return False

def createEdges(mat):
    adj=[]
    for y in range(len(mat)):
        for x in range(len(mat[y])):
            for outros in range(x,len(mat[y])):
                adj.append((mat[y][x],mat[y][outros]))
    for y in range(len(mat)):
        for x in range(len(mat[x])):
            for outros in range(y,len(mat)):
                adj.append((mat[y][x],mat[outros][x]))
            
    for y in range(len(mat)):
        for x in range(len(mat[y])):
            for yy in range(len(mat)):
                for xx in range(len(mat[yy])):
                    if checkSquare(x,y,xx,yy,int(math.sqrt(len(mat)))) and (mat[y][x],mat[yy][xx]) not in adj:
                        adj.append((mat[y][x],mat[yy][xx]))
    '''
    for (x,y) in adj:
        if (y,x) is adj:
            adj.remove((y,x))
    adj = list(set(adj))
    for (x,y) in adj:
        if x==y :
            adj.remove((x,y))'''
    adjq = [(x,y) for (x,y) in adj if x!=y and (y,x)]
    return adjq

In [7]:
def ip_color2(graph,k):
    

    # criar solver
    solver = pywraplp.Solver.CreateSolver('SCIP')
    #criar dicionario de variaveis x{i,j} 
    x = {}
    for i in graph:
        x[i] = {}
        for j in range(k):
            x[i][j] = solver.IntVar(0,1,'x[%i][%i]' % (i,j))

    my_list = []
      
    # vertices adjacentes tem cores diferentes
    for o in graph:
      for d in graph[o]:
            for j in range(k):
              if my_list.count(d) < 1:
                 solver.Add(x[o][j] + x[d][j] <= 1)
      my_list.append(o)  
         
         
       
                 


           
                  
            
    
    # cada vertice adjacente tem cores diferentes

    for i in graph:
        solver.Add(sum([x[i][j] for j in range(k)]) == 1)  # ou solver.Add(sum(list(x[i].values())) == 1) 

    # invocar solver e colorir o grafo

    stat = solver.Solve()
    if stat == pywraplp.Solver.OPTIMAL:

      # colorir

        for i in graph:
            for j in range(k):
                if round(x[i][j].solution_value()) == 1:
                    graph.nodes[i]['color'] = j+1
        return True
    else:
        return False

In [11]:
def converte(grafo):
    cores=[]
    for i in grafo:
        cores.append(grafo.nodes[i]['color'])
    solvedSudoku=np.reshape(cores,(int(math.sqrt(len(cores))),int(math.sqrt(len(cores)))))
    return solvedSudoku

Execução do código para n = 3.


In [12]:
pontos = [x+1 for x in range(9**2)]
pontos = np.reshape(pontos,(9,9))
edges=createEdges(pontos)
grafo5=nx.Graph(edges)
nx.set_node_attributes(grafo5,0,'color')
ti = time.perf_counter()
ip_color2(grafo5,9)
tf = time.perf_counter()
print(converte(grafo5))
print(f"Time {tf - ti: 0.5f} seconds")


[[3 8 9 6 2 7 5 4 1]
 [1 7 6 3 5 4 2 8 9]
 [4 2 5 8 1 9 6 3 7]
 [6 3 2 1 4 8 9 7 5]
 [5 9 4 2 7 6 3 1 8]
 [8 1 7 9 3 5 4 2 6]
 [9 5 1 4 8 2 7 6 3]
 [2 6 8 7 9 3 1 5 4]
 [7 4 3 5 6 1 8 9 2]]
Time  7.97319 seconds


Execução do código para n = 4.

In [ ]:
pontos = [x+1 for x in range(16**2)]
pontos = np.reshape(pontos,(16,16))
edges=createEdges(pontos)
grafo5=nx.Graph(edges)
nx.set_node_attributes(grafo5,0,'color')
ti = time.perf_counter()
ip_color2(grafo5,16)
tf = time.perf_counter()
print(converte(grafo5))
print(f"Time {tf - ti: 0.5f} seconds")

Execução do código para n = 5.

In [ ]:
pontos = [x+1 for x in range(25**2)]
pontos = np.reshape(pontos,(25,25))
edges=createEdges(pontos)
grafo5=nx.Graph(edges)
nx.set_node_attributes(grafo5,0,'color')
ti = time.perf_counter()
ip_color2(grafo5,25)
tf = time.perf_counter()
print(converte(grafo5))
print(f"Time {tf - ti: 0.5f} seconds")

Execução do código para n = 6.

In [ ]:
pontos = [x+1 for x in range(36**2)]
pontos = np.reshape(pontos,(36,36))
edges=createEdges(pontos)
grafo5=nx.Graph(edges)
nx.set_node_attributes(grafo5,0,'color')
ti = time.perf_counter()
ip_color2(grafo5,36)
tf = time.perf_counter()
print(converte(grafo5))
print(f"Time {tf - ti: 0.5f} seconds")